# External Dependencies
set(NWX_CATCH2_VERSION v2.x)
set(NWX_SPDLOG_VERSION ad0e89cbfb4d0c1ce4d097e134eb7be67baebb36)
set(NWX_LIBFORT_VERSION master)
set(NWX_ROCKSDB_VERSION v7.0.4)
set(NWX_LIBINT2_VERSION 2.6.0)
set(NWX_LIBINTX_VERSION master)

# TiledArray/MADNESS related
set(NWX_TILEDARRAY_VERSION fab5dc31fc10d88d381e8421d868d2185f164667)
set(NWX_MADNESS_VERSION 997e8b458c4234fb6c8c2781a5df59cb14b7e700)
set(NWX_CEREAL_VERSION v1.3.0)

# NWChemEx Related Libraries
set(NWX_UTILITIES_VERSION master)
set(NWX_PARALLELZONE_VERSION master)
set(NWX_PLUGINPLAY_VERSION master)
set(NWX_TENSORWRAPPER_VERSION master)
set(NWX_CHEMIST_VERSION master)
set(NWX_SIMDE_VERSION master)
set(NWX_MOKUP_VERSION master)
set(NWX_INTEGRALS_VERSION master)
set(NWX_GAUXC_VERSION feature/oop_seminumerical_k)
set(NWX_SCF_VERSION master)
set(NWX_MP2_VERSION master)
set(NWX_CHEMCACHE_VERSION master)
